export const ADD_TO_CART = "ADD_TO_CART"
export const UP_PRODUCTS_TO_CART = "UP_PRODUCTS_TO_CART"
export const DELETE_PRODUCT_OF_CART = "DELETE_PRODUCT_OF_CART"
export const INCREASE_AMOUNT_PRODUCT = "INCREASE_AMOUNT_PRODUCT"
export const DECREASE_AMOUNT_PRODUCT = "DECREASE_AMOUNT_PRODUCT"



export const SET_FOODS = "SET_FOODS"
export const SET_USER_INFOR = "SET_USER_INFOR"


